blank_issues_enabled: false
contact_links:
  - name: 📢 Questions & Discussions
    url: https://github.com/harshaldafade/trump-of-the-day-server/discussions
    about: Please ask and answer questions here.
